export const questionData = [
    {
      id: 1,
      title: "929",
      text: "很明显，国家贸易体系是一件好事",
      textEn: "it is clear that national trading system is a good thing",
    },
    {
      id: 2,
      title: "528",
      text: "目前公司的发展是不可预测的",
      textEn: "currently the growth of the company is unpredictable",
    },
    {
      id: 3,
      title: "826",
      text: "计算机对学生来说是一个很好的知识来源",
      textEn: "computer is a great source of knowledge for the students",
    },
    {
      id: 4,
      title: "814",
      text: "我们正以非常快的速度前进",
      textEn: "we are moving at a very fast pace",
    },
    {
      id: 5,
      title: "371",
      text: "时间表将在早上公布在网站上",
      textEn: "the timetable will be posted on the website in the morning",
    },
    {
      id: 6,
      title: "534",
      text: "所有学生都在家做作业",
      textEn: "all students do their homework at home",
    },
    {
      id: 7,
      title: "420",
      text: "道路安全措施可以减少事故",
      textEn: "road safety measures can reduce accidents",
    },
    {
      id: 8,
      title: "309",
      text: "由于停电，明天的讲座取消了",
      textEn: "tomorrow's lecture has been canceled due to the power cut",
    },
    {
      id: 9,
      title: "966",
      text: "我很高兴戈登教授刚刚加入我们学院",
      textEn: "i am glad that professor Gordon just joined our faculty",
    },
    {
      id: 10,
      title: "547",
      text: "只有在特殊情况下才能延期",
      textEn: "extension is only available under special circumstances",
    },
    {
      id: 11,
      title: "2466",
      text: "存档材料的数字扫描只需支付少量费用。",
      textEn: "digital scans of archived materials are provided with a small fee",
    },
    {
      id: 12,
      title: "2463",
      text: "可选教程在学期的最后一周提供",
      textEn: "optional tutorials are offered in the final week of a term",
    },
    {
      id: 13,
      title: "2459",
      text: "办公室在周一和周四新生研讨会后开放",
      textEn: "the office opens on monday and thursday following the freshman seminar",
    },
    {
      id: 14,
      title: "401",
      text: "学生们在学期期间住在宿舍里放",
      textEn: "students live in the residence hall during the term time",
    },
    {
      id: 15,
      title: "2458",
      text: "钙的营养价值每年都越来越受欢迎",
      textEn: "calcium's nutritional value enjoys growing popularity every year",
    },
    {
      id: 16,
      title: "2457",
      text: "这些年来，越来越多的学生是年轻人",
      textEn: "over the years, more and more students are young",
    },
    {
      id: 17,
      title: "2455",
      text: "在考试期间，电子设备必须留给监督者人",
      textEn: "during the examination electronic devices must be left to the supervisor",
    },
    {
      id: 18,
      title: "2454",
      text: "今天我们有一位演讲嘉宾，他是从加拿大来的",
      textEn: "today we have a guest speaker ,who is visiting from Canada",
    },
    {
      id: 19,
      title: "2452",
      text: "这是一场关于知识价值的辩论",
      textEn: "it is a debate about the value of knowledge",
    },
    {
      id: 20,
      title: "2450",
      text: "你的学期论文,应包括当前的社会问题",
      textEn: "your term papers,should include current social issues",
    },
    {
      id: 21,
      title: "2442",
      text: "即使是最有动力的学生也可能需要帮助来选择自己的职业",
      textEn: "even the most motivated students may need help to choose their careers",
    },
    {
      id: 22,
      title: "2439",
      text: "许多学生现在学习科学、技术、工程和数学",
      textEn: "many students are now studying science, technology, engineering and maths",
    },
    {
      id: 23,
      title: "2436",
      text: "我们鼓励学生在截止日期前完成申请",
      textEn: "we encourage students to complete applications before the deadline",
    },
    {
      id: 24,
      title: "2433",
      text: "视觉辅助对复习真的很有帮助",
      textEn: "visual aid is really helpful for a revising",
    },
    {
      id: 25,
      title: "2432",
      text: "我会尽快回来",
      textEn: "i will come back as soon as possible",
    },
    {
      id: 26,
      title: "909",
      text: "我研究的基本原理是展示城市生态系统的价值",
      textEn: "the rationale of my research is to present the value of the urban ecosystem",
    },
    {
      id: 27,
      title: "2428",
      text: "我们的学生参加了交流项目，以拓宽他们的视野",
      textEn: "our students have participated in exchange  programs to widen their horizons",
    },
    {
      id: 28,
      title: "2286",
      text: "整理课堂笔记可以提高学习效率",
      textEn: "keeping organized class notes makes study time more efficient",
    },
    {
      id: 29,
      title: "2108",
      text: "我们不再回复任何邮寄推荐信请求",
      textEn: "we no longer respond to any postal reference requests",
    },
    {
      id: 30,
      title: "2012",
      text: "关于这个话题没有理想的辩论",
      textEn: "there is no ideal debate on this topic",
    },
    {
      id: 31,
      title: "889",
      text: "有些人认为这是关心，有些人则认为这是鲁莽",
      textEn: "While some people regard it as care, others regard it as reckless.",
    },
    {
      id: 32,
      title: "2005",
      text: "社交媒体对新闻业有重大影响",
      textEn: "social media has a significant  impact on journalism",
    },
    {
      id: 33,
      title: "1999",
      text: "本科课程的完整列表可以在网站上找到",
      textEn: "the full list of undergraduate programs can be found on the website",
    },

    {
      id: 34,
      title: "1996",
      text: "广泛鼓励将考古学家的研究与社区项目相结合",
      textEn: "The integration of archeologists' studies with community projects is widely encouraged",
    },
    {
      id: 35,
      title: "1995",
      text: "会计专业的学生今天早上需要提交论文",
      textEn: "accountancy students need to submit their dissertations this week",
    },
    {
      id: 36,
      title: "1977",
      text: "政治假设是基于投票行为",
      textEn: "political assumptions are based on voting behaviors ",
    },
    {
      id: 37,
      title: "1974",
      text: "这周我不能发论文",
      textEn: "i can't hand out my dissertation this week",
    },
    {
      id: 38,
      title: "1975",
      text: "他的分析研究似乎是基于错误的前提",
      textEn: "his analysis study appears to be based on the false premise",
    },
    {
      id: 39,
      title: "1970",
      text: "每个班将选出一名学生代表",
      textEn: "one student representative will be selected from each class",
    },
    {
      id: 40,
      title: "1969",
      text: "研究人员发现，树木可以缓解压力和焦虑",
      textEn: "researchers found that trees can relieve stress and anxiety",
    },
    {
      id: 41,
      title: "1961",
      text: "我们致力于招聘来自各种背景和身份的候选人",
      textEn: "We are committed to recruiting candidates from all backgrounds and identities",
    },
    {
      id: 42,
      title: "1949",
      text: "许多农业工人来到伦敦东区寻找替代工作",
      textEn: "A lot of agricultural workers came to the East End to look for alternative work",
    },
    {
      id: 43,
      title: "1936",
      text: "在那段时间里，人们有大家庭作为一些孩子损失的保险",
      textEn: "during that time people had large families as an insurance against some children loss",
    },
    {
      id: 44,
      title: "1811",
      text: "下周关于殖民主义的话题将是核裁军",
      textEn: "the topic next week on colonialism will be the nuclear disarmament",
    },
    {
      id: 45,
      title: "1730",
      text: "他一直在寻找使工业和农业更紧密地结合在一起的方法。",
      textEn: "He was constantly looking for ways to bring industry and agriculture closer together",
    },
    {
      id: 46,
      title: "1727",
      text: "这所大学将寻求对这座略显空旷的剧院进行大规模翻新",
      textEn: "the university will seek a colossal renovation to the plain empty theater",

    },
    {
      id: 47,
      title: "1724",
      text: "我们将在下一节课上学习以下图片",
      textEn: "we will study the following pictures in the next lecture",
    },
    {
      id: 48,
      title: "1669",
      text: "今天的讲座取消了，因为演讲者病了",
      textEn: "today's lecture is canceled because the lecturer is ill",
    },
    {
      id: 49,
      title: "1596",
      text: "他想学医，但需要更多的资格证书",
      textEn: "he wants to study medicine but needs more qualifications",
    },
    {
      id: 50,
      title: "988",
      text: "保留收藏书籍有助于学生取得最大成就",
      textEn: "reserved collection books contribute to the most achievements of students",
    },
    {
      id: 51,
      title: "952",
      text: "有些人认为这是关心，而另一些人则认为这是鲁莽。",
      textEn: "Some people regarded it as care, while others regarded it as recklessness",
    },
     {
      id: 52,
      title: "750",
      text: "该学院包括两个分院，物理科学和社会科学",
      textEn: "The college includes two branches, physical and social sciences",
    },
    {
      id: 53,
      title: "589",
      text: "营养学是一个不断发展的领域",
      textEn: "the study of nutrition is a growing field",
    },
    {
      id: 54,
      title: "462",
      text: "生理学研究涉及传统科学和社会科学",
      textEn: "the study of physiology involves in traditional sciences and social sciences",
    },
    {
      id: 55,
      title: "445",
      text: "美国天文学家制定了将宇宙飞船降落在火星上的计划",
      textEn: "The American astronomers made a plan for landing a spaceship on Mars",
    },
    {
      id: 56,
      title: "442",
      text: "学生将学习古希腊的语言文学",
      textEn: "Students will study the language literature in ancient Greece",
    },
    {
      id: 57,
      title: "440",
      text: "在语言学习中，组织新类别的系统方法是必不可少的",
      textEn: "in language learning a systematic method of organizing new categories is essential",
    },
    {
      id: 58,
      title: "433",
      text: "有很多人熟悉这个过程",
      textEn: "there are a number of people familiar with this process",
    },
    {
      id: 59,
      title: "373",
      text: "地球的大气层主要由氧气和氮气组成",
      textEn: "The earth's atmosphere is primarily composed of oxygen and nitrogen gases",
    },
    {
      id: 60,
      title: "321",
      text: "所有学生会的学生都可以登记他们的名字以获得这项服务",
      textEn: "all the student union students can register their names to get that service",
    },
  ];