export const questionData = [
    {
      id: 1,
      title: "929",
      text: "很明显，国家贸易体系是一件好事",
      textEn: "it is clear that national trading system is a good thing",
    },
    {
      id: 2,
      title: "528",
      text: "目前公司的发展是不可预测的",
      textEn: "currently the growth of the company is unpredictable",
    },
    {
      id: 3,
      title: "826",
      text: "计算机对学生来说是一个很好的知识来源",
      textEn: "computer is a great source of knowledge for the students",
    },
    {
      id: 4,
      title: "814",
      text: "我们正以非常快的速度前进",
      textEn: "we are moving at a very fast pace",
    },
    {
      id: 5,
      title: "371",
      text: "时间表将在早上公布在网站上",
      textEn: "the timetable will be posted on the website in the morning",
    },
    {
      id: 6,
      title: "534",
      text: "所有学生都在家做作业",
      textEn: "all students do their homework at home",
    },
    {
      id: 7,
      title: "420",
      text: "道路安全措施可以减少事故",
      textEn: "road safety measures can reduce accidents",
    },
    {
      id: 8,
      title: "309",
      text: "由于停电，明天的讲座取消了",
      textEn: "tomorrow's lecture has been canceled due to the power cut",
    },
    {
      id: 9,
      title: "966",
      text: "我很高兴戈登教授刚刚加入我们学院",
      textEn: "i am glad that professor Gordon just joined our faculty",
    },
    {
      id: 10,
      title: "547",
      text: "只有在特殊情况下才能延期",
      textEn: "extension is only available under special circumstances",
    },
    {
      id: 11,
      title: "2466",
      text: "存档材料的数字扫描只需支付少量费用。",
      textEn: "digital scans of archived materials are provided with a small fee",
    },
    {
      id: 12,
      title: "2463",
      text: "可选教程在学期的最后一周提供",
      textEn: "optional tutorials are offered in the final week of a term",
    },
    {
      id: 13,
      title: "2459",
      text: "办公室在周一和周四新生研讨会后开放",
      textEn: "the office opens on monday and thursday following the freshman seminar",
    },
    {
      id: 14,
      title: "401",
      text: "学生们在学期期间住在宿舍里放",
      textEn: "students live in the residence hall during the term time",
    },
    {
      id: 15,
      title: "2458",
      text: "钙的营养价值每年都越来越受欢迎",
      textEn: "calcium's nutritional value enjoys growing popularity every year",
    },
    {
      id: 16,
      title: "2457",
      text: "这些年来，越来越多的学生是年轻人",
      textEn: "over the years, more and more students are young",
    },
    {
      id: 17,
      title: "2455",
      text: "在考试期间，电子设备必须留给监督者人",
      textEn: "during the examination electronic devices must be left to the supervisor",
    },
    {
      id: 18,
      title: "2454",
      text: "今天我们有一位演讲嘉宾，他是从加拿大来的",
      textEn: "today we have a guest speaker ,who is visiting from Canada",
    },
    {
      id: 19,
      title: "2452",
      text: "这是一场关于知识价值的辩论",
      textEn: "it is a debate about the value of knowledge",
    },
    {
      id: 20,
      title: "2450",
      text: "你的学期论文,应包括当前的社会问题",
      textEn: "your term papers,should include current social issues",
    },
    {
      id: 21,
      title: "2442",
      text: "即使是最有动力的学生也可能需要帮助来选择自己的职业",
      textEn: "even the most motivated students may need help to choose their careers",
    },
    {
      id: 22,
      title: "2439",
      text: "许多学生现在学习科学、技术、工程和数学",
      textEn: "many students are now studying science, technology, engineering and maths",
    },
    {
      id: 23,
      title: "2436",
      text: "我们鼓励学生在截止日期前完成申请",
      textEn: "we encourage students to complete applications before the deadline",
    },
    {
      id: 24,
      title: "2433",
      text: "视觉辅助对复习真的很有帮助",
      textEn: "visual aid is really helpful for a revising",
    },
    {
      id: 25,
      title: "2432",
      text: "我会尽快回来",
      textEn: "i will come back as soon as possible",
    },
    {
      id: 26,
      title: "909",
      text: "我研究的基本原理是展示城市生态系统的价值",
      textEn: "the rationale of my research is to present the value of the urban ecosystem",
    },
    {
      id: 27,
      title: "2428",
      text: "我们的学生参加了交流项目，以拓宽他们的视野",
      textEn: "our students have participated in exchange  programs to widen their horizons",
    },
    {
      id: 28,
      title: "2286",
      text: "整理课堂笔记可以提高学习效率",
      textEn: "keeping organized class notes makes study time more efficient",
    },
    {
      id: 29,
      title: "2108",
      text: "我们不再回复任何邮寄推荐信请求",
      textEn: "we no longer respond to any postal reference requests",
    },
    {
      id: 30,
      title: "2012",
      text: "关于这个话题没有理想的辩论",
      textEn: "there is no ideal debate on this topic",
    },
  ];